# Navigation Links (English)
main:
  - name: Home
    url: ""
    weight: 10

  - name: News
    url: news/
    weight: 20

  - name: Research
    url: research/
    weight: 30

  - name: Achievements
    url: "#"
    weight: 40
    hasChildren: true

  - name: Publications
    url: publication/
    parent: Achievements
    weight: 41

  - name: Presentations
    url: event/
    parent: Achievements
    weight: 42

  - name: Grants
    url: project/
    parent: Achievements
    weight: 43

  - name: Research Digest
    url: post/
    parent: Achievements
    weight: 44

  - name: CV
    url: cv/
    weight: 50
